// traits.ts

export const traits = [
  "minimalistic",
  "warm",
  "technical",
  "playful",
  "luxury",
  "organic",
  "structured",
    "chaotic",
    "soft",
  "aesthetic",
  "functional",
    "trending",
    "viral",
    "calm",
    "energetic",
    "introverted",
    "extroverted",
    "thinker",
    "feeler",
    "adventurous",
    "cautious",
    "innovative",
    "traditional",
    "soothing",
    "pleasure_seeking",
    "sophisticated",
    "quirky",
    "spontaneous",
    "creative",
    "disciplined",
    "fantasy",
    "organized",
    "social",
    "status_oriented",
    "escapeism",
    "freedom",
    "nostalgia",
    "status",
] as const;

export type Trait = typeof traits[number];